### ISSUE TITLE
Compatibility with v1.8.0.beta10 +179 

### ISSUE THREAD

**Issue by theodotos** [waynegraham/discourse-import-bbpress#4]
Is this plugin compatible with the dockerized recent versions of Discource?

**Comment by waynegraham** [comment]
@theodotos I don't think so (this is pretty old). I would take a look at https://meta.discourse.org/t/migrating-from-bbpress-wordpress-plugin-to-discourse/48876 for using the "official" migration plugin included in Discourse.

**Comment by theodotos** [comment]
Thanks Wayne. I'll give it a try.
